apiVersion: apps/v1
kind: Deployment
metadata:
  name: filevault-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filevault
  template:
    metadata:
      labels:
        app: filevault
    spec:
      containers:
        - name: filevault-app
          image: filevaultregistrymariana.azurecr.io/filevault:placeholder
          ports:
            - containerPort: 3000
          env:
            - name: AZURE_STORAGE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: filevault-config
                  key: STORAGE_NAME
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: filevault-config
                  key: STORAGE_KEY
            - name: AZURE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: filevault-config
                  key: CONTAINER_NAME
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"